// <auto-generated />
namespace VisiProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CategoriaIdToProjetoModel2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CategoriaIdToProjetoModel2));
        
        string IMigrationMetadata.Id
        {
            get { return "201408062205588_CategoriaIdToProjetoModel2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
